version: 1.0.0

# GO SDK使用的客户端部分。
client:
  # 这个应用程序是属于哪个组织的，这里就填那个组织的组织名
  organization: org1

  # 日志登记
  logging:
    level: info

  # MSP证书的根路径
  cryptoconfig:
    path: ${GOPATH}/src/github.com/togettoyou/blockchain-real-estate/deploy/crypto-config

  # 默认即可，以下都是可选（optional）的配置
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp

  # 这里配置的是加密组件的一些属性，默认即可
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

# 通道相关配置
channels:
  # 通道的名称
  assetschannel:
    # 【必须】orderer的配置，填orderer的域名
    orderers:
      - orderer.blockchainrealestate.com

    # 【必须】节点配置
    peers:
      # 填写这个应用程序所属组织的Peer的域名
      peer0.org1.blockchainrealestate.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org1.blockchainrealestate.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # 【可选】策略配置
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

# 组织配置，列举了参与该网络的所有组织
organizations:
  # 组织的名称
  org1:
    # 该组织的MSPID
    mspid: Org1MSP

    # 这个组织的MSP证书路径
    cryptoPath:  peerOrganizations/org1.blockchainrealestate.com/users/{username}@org1.blockchainrealestate.com/msp

    # 这个组织下属的节点
    peers:
      - peer0.org1.blockchainrealestate.com
      - peer1.org1.blockchainrealestate.com

    certificateAuthorities:
    #- ca.org1.example.com

  # orderer组织
  ordererorg:
    # orderer组织的MSPID
    mspID: "OrdererMSP"

    # orderer组织的MSP证书路径
    cryptoPath: ordererOrganizations/blockchainrealestate.com/users/{username}@blockchainrealestate.com/msp

# 指定orderer
orderers:
  orderer.blockchainrealestate.com:
    url: 127.0.0.1:7050

    # grpc配置
    grpcOptions:
      ssl-target-name-override: orderer.blockchainrealestate.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true # 非tls连接

# 指定peer
peers:
  peer0.org1.blockchainrealestate.com:
    url: 127.0.0.1:27051
    eventUrl: 127.0.0.1:27053

    # grpc配置
    grpcOptions:
      ssl-target-name-override: peer0.org1.blockchainrealestate.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true